path:
  data:
    root: 'data'
    raw:
      root: 'data/raw'
      train: 'data/raw/train'
      test: 'data/raw/test'

data:
  size: 384
  stats:
    min: -1215.0
    max: 1930.0
    mean: 0.3865
    std: 0.03485