name: segmenting-subsurface-env
dependencies:
  - python=3.10.*
  - pip
  - pip:
      - pyyaml
      - tqdm
      - torch
      - torchvision
      - numpy
      - transformers
      - pytorch-lightning
      - wandb
      - matplotlib
      - scikit-learn
      - jupyter
      - opencv-python