path:
  data:
    root: 'data'
    raw:
      root: 'data/raw'
      train: 'data/raw/train'
      test: 'data/raw/test'
  models:
    root: 'models'

data:
  stats:
    mean: 0.3865
    std: 0.03485
