path:
  data:
    root: 'data'
    raw:
      root: 'data/raw'
      train: 'data/raw/train'
      test: 'data/raw/test'
    processed:
      root: 'data/processed'
      train: 'data/processed/train'
      test: 'data/processed/test'
  models:
    root: 'models'

data:
  mean: 0.3865
  std: 0.03485
