path:
  data:
    root: 'data'
    raw:
      root: 'data/raw'
      train: 'data/raw/train'
      test: 'data/raw/test'
    processed:
      root: 'data/processed'
      train: 'data/processed/train'
      test: 'data/processed/test'
  models:
    root: 'models'
  reports:
    root: 'reports'
    figures: 'reports/figures'
  sumbmissions:
    root: 'submissions'

wandb:
  entity: 'association-rosia'
  project: 'segmenting-subsurface'

data:
  min: -1215.0
  max: 1930.0
  mean: 0.3865
  std: 0.03485