dry: true

random_state: 42
max_epochs: 100

model_id: 'facebook/mask2former-swin-base-coco-instance'
num_channels: 3
contrast_factor: 25

model_prompt: 'k13mlcpr'

dilation: 30
val_size: 0.2
dim: '0'
label_type: 'instance'

batch_size: 16
num_workers: 23

lr: 0.0001