dry: false

random_state: 42
max_epochs: 100
criterion: 'JaccardCrossEntropyLoss'

model_id: 'nvidia/segformer-b3-finetuned-ade-512-512'
num_labels: 1
num_channels: 3
contrast_factor: 25

# dilation: 30
dilation: 1
val_size: 0.2
dim: '0'

label_type: 'layer'

batch_size: 16
num_workers: 23

lr: 0.00002