dry: true

random_state: 42
max_epochs: 50
criterion: 'JaccardBCEWithLogitsLoss'

model_id: 'nvidia/segformer-b5-finetuned-ade-640-640'
num_labels: 1
num_channels: 3

dilation: 30
val_size: 0.2
dim: '0'

batch_size: 16
num_workers: 23

lr: 0.005