dry: false

random_state: 42
max_epochs: 50
criterion: 'JaccardBCEWithLogitsLoss'

#model_id: 'nvidia/segformer-b5-finetuned-ade-640-640'
model_id: 'nvidia/segformer-b0-finetuned-ade-512-512'
num_labels: 1
num_channels: 3
contrast_factor: 1

dilation: 30
val_size: 0.2
dim: '0'
label_type: 'layer'

batch_size: 16
num_workers: 23

lr: 0.0001