dry: false

random_state: 42
max_epochs: 10

model_id: 'nvidia/segformer-b0-finetuned-ade-512-512'
num_labels: 1
num_channels: 3

dilation: 30
val_size: 0.2
dim: '0'

batch_size: 16
num_workers: 23

lr: 0.0001