random_state: 42
max_epochs: 3

#model_id: 'facebook/mask2former-swin-tiny-coco-instance'
model_id: 'nvidia/segformer-b0-finetuned-ade-512-512'
num_labels: 100
num_channels: 3

dataset_size: null
val_size: 0.2
dim: '0,1'

batch_size: 16
num_workers: 95

lr: 0.00006