random_state: 42
max_epochs: 3

model_id: 'nvidia/segformer-b5-finetuned-ade-640-640'
num_labels: 100 # verify in the starter notebook
num_channels: 3

dataset_size: null
val_size: 0.1
dim: '0,1'

batch_size: 16
num_workers: 95

lr: 0.001